import React from 'react'

const Prova = () => {
    return (
        <>
            <div style="
    background-color:#0b0f1a;
    padding:24px;
    font-family: 'Segoe UI', Roboto, Arial, sans-serif;
    color:#e6e8ee;
  ">
                <div style="
      max-width:600px;
      margin:0 auto;
      border:1px solid #1f2937;
      border-radius:12px;
      overflow:hidden;
      background:linear-gradient(180deg, #0f172a, #020617);
      box-shadow:0 0 40px rgba(0,0,0,0.6);
    ">
                    <div style="
        padding:20px 24px;
        background:rgba(15,23,42,0.9);
        border-bottom:1px solid #1f2937;
      ">
                        <p style="
          margin:0;
          font-size:11px;
          letter-spacing:0.35em;
          text-transform:uppercase;
          color:#94a3b8;
        ">
                            System Notification
                        </p>
                        <h2 style="
          margin:8px 0 0 0;
          font-size:22px;
          font-weight:800;
          color:#e5e7eb;
        ">
                            New Help Request
                        </h2>
                    </div>

                    <div style="padding:24px;">
                        <div style="
          margin-bottom:16px;
          padding:16px;
          background:rgba(2,6,23,0.6);
          border:1px solid #1f2937;
          border-radius:10px;
        ">
                            <p style="margin:0 0 6px 0; color:#94a3b8; font-size:12px;">
                                PLAYER NAME
                            </p>
                            <p style="margin:0; font-size:16px; font-weight:600;">
                                rrr
                            </p>
                        </div>

                        <div style="
          margin-bottom:16px;
          padding:16px;
          background:rgba(2,6,23,0.6);
          border:1px solid #1f2937;
          border-radius:10px;
        ">
                            <p style="margin:0 0 6px 0; color:#94a3b8; font-size:12px;">
                                CONTACT EMAIL
                            </p>
                            <p style="margin:0; font-size:15px;">
                                rrr@gmail.com
                            </p>
                        </div>

                        <div style="
          padding:16px;
          background:rgba(2,6,23,0.6);
          border:1px solid #334155;
          border-radius:10px;
        ">
                            <p style="
            margin:0 0 8px 0;
            color:#eab308;
            font-size:12px;
            letter-spacing:0.2em;
            text-transform:uppercase;
          ">
                                Message Content
                            </p>
                            <div style="
            font-size:14px;
            line-height:1.6;
            white-space:pre-wrap;
            color:#e5e7eb;
          ">
                                rrr
                            </div>
                        </div>
                    </div>

                    <div style="
        padding:16px 24px;
        border-top:1px solid #1f2937;
        background:rgba(15,23,42,0.8);
        text-align:center;
      ">
                        <p style="
          margin:0;
          font-size:11px;
          color:#64748b;
        ">
                            This message was generated by the System.<br />
                            Solo Leveling — Help Interface
                        </p>
                    </div>

                </div>
            </div>

        </>
    )
}

export default Prova